export const data = {
    sip: {
        title: "SIP Calculator",
        what: "A Systematic Investment Plan (SIP) is a disciplined investment strategy where you contribute a fixed amount into mutual funds at regular intervals. It automates savings and leverages market cycles to build long-term wealth.",
        why: "It utilizes 'Rupee Cost Averaging'—buying more units when prices are low and fewer when high. This eliminates the need to time the market and harnesses the power of compounding to reach goals like retirement or education.",
        deepDive: "The 'Time-Value' multiplier is the core of SIP success. Starting a SIP just 5 years earlier can result in a maturity corpus that is nearly double, as the exponential growth curve steepens significantly in the final years.",
        formula: "FV = P × ({[1 + i]^n – 1} / i) × (1 + i)",
        variables: [{ k: "P", v: "Monthly Installment" }, { k: "i", v: "Periodic Rate" }, { k: "n", v: "Tenure (Months)" }],
        specs: [{ feature: "Risk", value: "Market Linked" }, { feature: "Strategy", value: "Cost Averaging" }],
        pros: ["Disciplined Savings", "Averages Volatility", "Compound Growth"],
        cons: ["Market Risk", "No Fixed Returns", "Short-term Fluctuation"],
        tips_tricks: ["The 10% Step-up Secret: Increasing SIP annually can reach your target 5 years faster.", "Never stop SIPs during a bear market; that's when wealth is actually made.", "Link every SIP to a specific life goal for better retention."]
    },
    brokerage: {
        title: "Brokerage & Tax Terminal",
        what: "This terminal analyzes the total cost of a trade beyond the execution price. It accounts for broker commissions and statutory government taxes like STT, GST, SEBI fees, and State Stamp Duty.",
        why: "Traders operate on thin margins where taxes can exceed the brokerage itself. This tool identifies your exact 'Break-even Price'—the minimum movement needed just to cover trading costs.",
        deepDive: "Statutory charges like STT are significantly higher for delivery trades than intraday. For scalpers, understanding the impact of GST on transaction fees is the difference between a profitable day and a net loss.",
        formula: "Net P&L = (Sell - Buy) - Total Charges",
        variables: [{ k: "STT", v: "Govt. Transaction Tax" }, { k: "GST", v: "18% on Fees" }, { k: "SEBI", v: "Regulatory Fee" }],
        specs: [{ feature: "Compliance", value: "Finance Act 2025" }, { feature: "Mode", value: "Intraday / Delivery" }],
        pros: ["Tax Transparency", "Break-even Analysis", "Accurate Net P&L"],
        cons: ["Varies by State", "Excludes DP Charges", "Static Slab logic"],
        tips_tricks: ["Intraday trades charge STT only on the sell side, saving 50% on government levies.", "Use flat-fee brokers for high volumes to cap your commission impact.", "Always calculate taxes before entering trades with less than 0.5% target."]
    },
    emi: {
        title: "Loan EMI Amortization Matrix",
        what: "An Equated Monthly Installment (EMI) is a fixed payment amount made by a borrower to a lender. It balances the principal repayment and the interest servicing over a specific tenure.",
        why: "Initial EMIs are nearly 80% interest. Visualizing the 'Amortization Schedule' helps you plan prepayments to drastically reduce the total interest burden and exit debt years ahead of schedule.",
        deepDive: "The 'Interest Pre-loading' logic means banks take their profit first. Prepaying just 1-2 extra EMIs in the first 3 years of a 20-year loan can save you up to 25% of the total interest cost.",
        formula: "E = P × r × (1 + r)^n / ((1 + r)^n – 1)",
        variables: [{ k: "P", v: "Principal Amount" }, { k: "r", v: "Monthly Interest" }, { k: "n", v: "Tenure (Months)" }],
        specs: [{ feature: "Method", value: "Reducing Balance" }, { feature: "Credit Link", value: "CIBIL Impact Score" }],
        pros: ["Fixed Roadmap", "Tax Benefits (Home Loan)", "Monthly Stability"],
        cons: ["Interest Heavy Start", "Default Risk", "Prepayment Penalty"],
        tips_tricks: ["One-Extra Rule: Paying one extra EMI annually can cut a 20-year tenure to 15 years.", "Round-up Strategy: Pay ₹25,000 instead of ₹24,200 to shave off months of interest.", "Refinance early if market interest rates drop by more than 0.5%."]
    },
    lumpsum: {
        title: "Lumpsum Wealth Estimator",
        what: "A Lumpsum investment is a one-time deposit of a large capital sum into a financial instrument. It calculates the terminal value based on a specific expected CAGR.",
        why: "Perfect for windfalls like bonuses or property sales. It helps you decide whether to invest everything at once or use an STP (Systematic Transfer Plan) to mitigate entry-point risk.",
        deepDive: "Lumpsum returns are sensitive to the 'Entry Valuation'. Investing when the Nifty PE ratio is below 20 historically yields 15%+ CAGR, whereas investing at peaks reduces the margin of safety.",
        formula: "A = P (1 + r/n)^nt",
        variables: [{ k: "P", v: "Principal" }, { k: "r", v: "Return Rate" }, { k: "t", v: "Tenure (Years)" }],
        specs: [{ feature: "Type", value: "Single Deposit" }, { feature: "Asset", value: "Equity/Debt/Gold" }],
        pros: ["High Absolute Gains", "Simple Tracking", "No Periodic Commitment"],
        cons: ["High Entry Risk", "Volatility Impact", "Timing Dependence"],
        tips_tricks: ["Rule of 72: Divide 72 by your expected return to see how fast your lumpsum doubles.", "Never invest a lumpsum at market all-time highs; wait for a 5% healthy correction.", "Use Lumpsum for debt-free assets like SGBs to lock in interest + appreciation."]
    },
    ppf: {
        title: "PPF Safe-Savings Terminal",
        what: "Public Provident Fund (PPF) is a sovereign-backed long-term savings tool. It offers a 15-year tenure with interest rates set quarterly by the Ministry of Finance.",
        why: "It provides the coveted 'EEE' status—Exempt on Investment, Exempt on Interest, and Exempt on Maturity. It is the safest retirement pillar for conservative Indian investors.",
        deepDive: "The '5th Day' logic: PPF interest is calculated on the minimum balance between the 5th and the end of the month. Depositing on the 6th means losing 30 days of compounding interest.",
        formula: "A = P [({(1 + i)^n} - 1) / i]",
        variables: [{ k: "P", v: "Annual Deposit" }, { k: "i", v: "Interest Rate" }, { k: "n", v: "15-50 Years" }],
        specs: [{ feature: "Security", value: "Govt Guarantee" }, { feature: "Tax Status", value: "EEE Category" }],
        pros: ["100% Capital Safety", "Tax-Free Maturity", "Loan Facility"],
        cons: ["15-Year Lock-in", "₹1.5L Annual Limit", "Rate Fluctuations"],
        tips_tricks: ["April Window: Invest the full ₹1.5L between April 1st and 5th to maximize a full year's compounding.", "The Extension Hack: Extend in blocks of 5 years to keep the tax-free interest growing indefinitely.", "Partial withdrawals are allowed after 6 years for life emergencies without closing the account."]
    },
    goal: {
        title: "Goal Precision Planner",
        what: "This tool reverse-calculates the savings required today to reach a specific financial target in the future, adjusted for inflation and expected returns.",
        why: "It replaces 'hope' with 'math.' Instead of saving randomly, you identify the exact SIP amount needed for a child's Ivy League education or a dream retirement villa.",
        deepDive: "Inflation is the silent wealth killer. A ₹50 Lakh goal in 2025 will require nearly ₹1.2 Crore in 2040 at 6% inflation. This terminal ensures your target corpus maintains its purchasing power.",
        formula: "Required = Goal / (1 + r)^n",
        variables: [{ k: "Target", v: "Future Cost" }, { k: "Inflation", v: "Price Rise %" }, { k: "Years", v: "Time Horizon" }],
        specs: [{ feature: "Focus", value: "Target-Based" }, { feature: "Analysis", value: "Backward Induction" }],
        pros: ["Clarity of savings", "Realistic Roadmap", "Prevents Under-saving"],
        cons: ["Assumption Dependent", "Inflation Variance", "Life Change Shifts"],
        tips_tricks: ["Always assume 7% inflation for education and 10% for healthcare goals.", "Review your goal progress every year and adjust for salary increments.", "Diversify the goal corpus across Equity and Debt based on the years remaining."]
    },
    retirement: {
        title: "Retirement Corpus Calculator",
        what: "This terminal estimates the total 'Nest Egg' required to sustain your current lifestyle once your active income stops, accounting for life expectancy and inflation.",
        why: "Retirement is the only goal you cannot take a loan for. This tool helps you avoid 'Longevity Risk'—the danger of outliving your savings in your sunset years.",
        deepDive: "The '4% Withdrawal Rule' is the global standard. If your corpus is 25x your annual expenses, you can safely withdraw 4% adjusted for inflation every year for 30+ years without depleting the base.",
        formula: "Corpus = Annual Expenses / Safe Withdrawal Rate",
        variables: [{ k: "Exp", v: "Monthly Spending" }, { k: "Life", v: "Expectancy" }, { k: "Inflation", v: "Price Rise" }],
        specs: [{ feature: "Horizon", value: "Ultra Long-term" }, { feature: "Tax", value: "Post-Withdrawal" }],
        pros: ["Financial Independence", "Medical Security", "Peace of Mind"],
        cons: ["Rising Medical Costs", "Tax Slab Changes", "Inflation Spikes"],
        tips_tricks: ["Aim for a corpus that is 30x your current annual expenses for a stress-free retirement.", "Start a pension SIP as soon as you get your first salary to benefit from 35 years of compounding.", "Include a separate medical emergency fund outside your retirement corpus calculation."]
    },
    fd: {
        title: "FD Interest Matrix",
        what: "A Fixed Deposit (FD) is a banking instrument that offers a guaranteed interest rate for a chosen tenure. It is the most popular low-risk savings tool in India.",
        why: "Ideal for short-term parking of funds where capital preservation is the primary goal. It is liquid (with minor penalty) and provides higher interest than a savings account.",
        deepDive: "The 'Real Return' of an FD is often negative. If an FD gives 7% and inflation is 6%, your real gain is only 1%. Furthermore, FD interest is taxable, making post-tax returns even lower.",
        formula: "A = P (1 + r/n)^nt",
        variables: [{ k: "P", v: "Deposit Amount" }, { k: "r", v: "Interest Rate" }, { k: "n", v: "Compounding Freq" }],
        specs: [{ feature: "Risk", value: "Zero (DICGC)" }, { feature: "Liquidity", value: "Immediate (Penalty)" }],
        pros: ["Guaranteed Returns", "Senior Citizen Bonus", "Loan Facility"],
        cons: ["Taxable Interest", "Lower than Inflation", "Tenure Lock"],
        tips_tricks: ["Laddering Strategy: Split ₹5 Lakh into 5 FDs of 1, 2, 3, 4, and 5 years for constant liquidity.", "Avoid long-term FDs when interest rates are expected to rise soon.", "Ensure the bank is DICGC insured for up to ₹5 Lakh safety."]
    },
    gold: {
        title: "Gold Investment Matrix",
        what: "This terminal tracks the appreciation of gold as an asset class, including physical gold, digital gold, and Sovereign Gold Bonds (SGBs).",
        why: "Gold is the ultimate hedge against currency devaluation and stock market crashes. It maintains its purchasing power over centuries and provides high liquidity in times of crisis.",
        deepDive: "Sovereign Gold Bonds (SGB) are the smartest way to own gold. You get the market price appreciation plus a fixed 2.5% annual interest, with zero storage costs or making charges.",
        formula: "Value = (Qty × Rate) + SGB Interest",
        variables: [{ k: "Price", v: "24K Market Rate" }, { k: "Qty", v: "Grams Held" }, { k: "SGB", v: "Interest (2.5%)" }],
        specs: [{ feature: "Asset", value: "Precious Metal" }, { feature: "Hedge", value: "Inflation/Crisis" }],
        pros: ["Global Liquidity", "Crisis Protection", "Inflation Hedge"],
        cons: ["No Monthly Yield", "Making Charges", "Storage/Theft Risk"],
        tips_tricks: ["Hold 10% of your portfolio in gold to reduce overall volatility during market crashes.", "Buy Digital Gold for small savings but convert to SGB for long-term holding.", "Track the USD-INR exchange rate, as gold prices in India are sensitive to currency fluctuations."]
    },
    ipo: {
        title: "IPO Profit/Gain Matrix",
        what: "This tool calculates the potential listing gains of an Initial Public Offering (IPO) based on the Grey Market Premium (GMP) and issue price.",
        why: "IPOs offer a chance to enter high-growth companies early. This tool helps you calculate your ROI based on the number of lots allotted and the expected listing price.",
        deepDive: "Over-subscription is the key to listing gains. If an IPO is subscribed 50x in the HNI and QIB categories, it creates a supply-demand gap that drives the price up on the listing day.",
        formula: "Profit = (Listing - Issue) × Quantity",
        variables: [{ k: "Issue", v: "Offer Price" }, { k: "Lot", v: "Shares per Lot" }, { k: "GMP", v: "Grey Market Premium" }],
        specs: [{ feature: "Market", value: "Primary" }, { feature: "Type", value: "Equity" }],
        pros: ["Quick Listing Gains", "Early Entry", "Standardized Price"],
        cons: ["Low Allotment Probability", "Listing Loss Risk", "Short-term Volatility"],
        tips_tricks: ["Check the 'Subscription Status' on the final day before applying to gauge institutional interest.", "Apply via multiple family member PANs to increase your allotment probability in the retail category.", "Always have an 'Exit Plan' for the listing day; don't hold speculative IPOs for the long term."]
    },
    cagr: {
        title: "CAGR Tool",
        what: "Compound Annual Growth Rate (CAGR) measures the mean annual growth of an investment over a period longer than one year.",
        why: "It is the only accurate way to compare the performance of different asset classes (e.g., Stocks vs. Gold) because it smoothes out volatility into a single annualized figure.",
        deepDive: "CAGR assumes 'reinvestment'. It calculates the rate at which an investment would have grown if it had grown at a steady rate each year. It is vital for evaluating Mutual Fund and Real Estate performance.",
        formula: "CAGR = [(EV / BV)^(1/n)] - 1",
        variables: [{ k: "EV", v: "Ending Value" }, { k: "BV", v: "Start Value" }, { k: "n", v: "Tenure (Years)" }],
        specs: [{ feature: "Metric", value: "Geometric Mean" }, { feature: "Usage", value: "Performance Check" }],
        pros: ["Accurate Growth Tracking", "Standardized Metric", "Smoothes Volatility"],
        cons: ["Ignores Timing Risk", "Linear Projection", "Not for Short-term"],
        tips_tricks: ["Use CAGR for any investment longer than 3 years to see the real growth.", "Compare CAGR with the Benchmark index to see if your investment outperformed the market.", "Always look at post-tax CAGR to see your actual purchasing power gain."]
    },
    epf: {
        title: "EPF Retirement Tracker",
        what: "Employee Provident Fund (EPF) is a retirement benefit scheme for salaried employees where both the employer and employee contribute 12% of the basic salary.",
        why: "It creates a massive retirement fund automatically. It is one of the few debt instruments that offers high interest with sovereign safety and triple tax benefits.",
        deepDive: "EPF is the most powerful compounding tool for the Indian middle class. If you start at age 22 and never withdraw, the employer's matching contribution alone can fund a comfortable retirement lifestyle.",
        formula: "A = (Monthly Cont. × Months) + Interest",
        variables: [{ k: "Salary", v: "Basic + DA" }, { k: "Rate", v: "EPFO Interest Rate" }],
        specs: [{ feature: "Contributor", value: "Employee/Employer" }, { feature: "Guarantee", value: "Sovereign" }],
        pros: ["Matching Contribution", "Automatic Discipline", "Tax-Free Maturity"],
        cons: ["Salary Dependent", "Withdrawal Restrictions", "Fixed Interest"],
        tips_tricks: ["Always transfer your EPF UAN when switching jobs; withdrawing breaks the compounding chain.", "Increase your VPF (Voluntary Provident Fund) if you want safe, high-interest tax-free returns beyond 12%.", "Nominate your family members in the UAN portal to ensure smooth transfer of funds."]
    },
    taxfd: {
        title: "Tax-Saving FD Planner",
        what: "This is a special Fixed Deposit with a mandatory 5-year lock-in period that qualifies for tax deductions under Section 80C.",
        why: "It is for risk-averse investors who want to save tax but don't want the volatility of ELSS or the long 15-year lock-in of PPF.",
        deepDive: "Unlike normal FDs, you cannot take a loan against a Tax-Saving FD, and you cannot withdraw it prematurely. The interest earned is added to your income and taxed as per your slab.",
        formula: "Tax Saved = Invested × Tax Slab",
        variables: [{ k: "Invest", v: "Up to ₹1.5L" }, { k: "Tenure", v: "Fixed 5 Years" }],
        specs: [{ feature: "Lock-in", value: "5 Years" }, { feature: "Benefit", value: "Sec 80C" }],
        pros: ["Guaranteed Returns", "80C Tax Benefit", "Zero Management"],
        cons: ["5-Year Total Lock-in", "Taxable Interest", "No Loan Facility"],
        tips_tricks: ["Only use this if your 80C limit (₹1.5L) isn't already filled by EPF, Insurance, or PPF.", "Check interest rates across different banks; sometimes small finance banks offer 1-2% more on Tax FDs.", "Remember that the tax benefit is only on the investment, not the interest."]
    },
    swp: {
        title: "SWP Pension Terminal",
        what: "A Systematic Withdrawal Plan (SWP) allows you to withdraw a fixed amount from your mutual fund corpus at regular intervals, effectively creating a self-made pension.",
        why: "It is the most tax-efficient way to generate monthly income post-retirement. Unlike FD interest or annuities, only the 'Capital Gain' portion of the withdrawal is taxed.",
        deepDive: "SWP manages 'Sequence of Returns' risk. By withdrawing a fixed amount, you sell more units when the market is low and fewer when high, which is the inverse of a SIP.",
        formula: "Remaining = [P(1+r)] - W",
        variables: [{ k: "Corpus", v: "Total Fund" }, { k: "Withdrawal", v: "Monthly Payout" }, { k: "r", v: "Annual Return" }],
        specs: [{ feature: "Goal", value: "Regular Income" }, { feature: "Tax", value: "Capital Gains" }],
        pros: ["Tax Efficiency", "Regular Cash Flow", "Capital Appreciation"],
        cons: ["Corpus Depletion Risk", "Market Volatility", "Inflation Impact"],
        tips_tricks: ["Keep your withdrawal rate at 5-6% to ensure your corpus lasts for 25+ years.", "Use Debt-oriented hybrid funds for SWP to minimize short-term volatility in your monthly payout.", "Review your withdrawal amount every 2 years to adjust for lifestyle inflation."]
    },
    gsec: {
        title: "G-Sec Bond Terminal",
        what: "Government Securities (G-Secs) are debt instruments issued by the RBI on behalf of the Government to finance the country's fiscal deficit.",
        why: "They offer the absolute highest degree of safety (Zero default risk). They are now available to retail investors through the RBI Retail Direct portal for steady long-term income.",
        deepDive: "G-Secs have 'Duration Risk.' When interest rates in the economy fall, the price of existing bonds goes up. You can earn through both periodic interest (coupons) and capital appreciation.",
        formula: "Yield = (Coupon / Price) × 100",
        variables: [{ k: "Coupon", v: "Fixed Interest" }, { k: "Price", v: "Market Value" }],
        specs: [{ feature: "Safety", value: "Sovereign" }, { feature: "Tenure", value: "Up to 40 Years" }],
        pros: ["Zero Default Risk", "Periodic Interest", "High Tenure Options"],
        cons: ["Interest Rate Risk", "Lower Return than Equity", "Limited Liquidity"],
        tips_tricks: ["Lock in long-term G-Secs when interest rates are at a cyclical peak for high lifetime yields.", "G-Secs are better than FDs for the 30% tax bracket if you hold them through debt mutual funds (indexation benefits).", "Use G-Secs as the 'Safety' foundation of your portfolio, keeping 20-30% allocation here."]
    }
};